name: CI/CD for Churn Prediction
 
on:
  push:
    branches:
      - main
    paths:
      - train.py
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
 
      - name: Install AWS Elastic Beanstalk CLI
        run: |
          python -m pip install --upgrade pip
          pip install --user awsebcli
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          eb --version
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
 
      - name: Build Docker Image
        run: |
          docker build -t nurcia-churn .
 
      - name: Run Tests in Docker
        run: |
          docker run --rm nurcia-churn python -m pytest -q
 
      - name: Initialize Elastic Beanstalk Application
        run: |
          eb init -p docker nurcia-churn --region eu-north-1
 
      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy Env-nurcia-churn
